/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SgCopyright {
        "color"?: string;
        "company": string;
        "from": string;
        "placement": 'left' | 'right' |'center';
    }
}
declare global {
    interface HTMLSgCopyrightElement extends Components.SgCopyright, HTMLStencilElement {
    }
    var HTMLSgCopyrightElement: {
        prototype: HTMLSgCopyrightElement;
        new (): HTMLSgCopyrightElement;
    };
    interface HTMLElementTagNameMap {
        "sg-copyright": HTMLSgCopyrightElement;
    }
}
declare namespace LocalJSX {
    interface SgCopyright {
        "color"?: string;
        "company"?: string;
        "from"?: string;
        "placement"?: 'left' | 'right' |'center';
    }
    interface IntrinsicElements {
        "sg-copyright": SgCopyright;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sg-copyright": LocalJSX.SgCopyright & JSXBase.HTMLAttributes<HTMLSgCopyrightElement>;
        }
    }
}
